"""Build-time tool: embed the OAuth client configuration into the executable.

Reads ``credentials.json`` (development file, git-ignored) and generates
``embedded_secrets.py`` containing the client config as a single base64
blob. The generated module is compiled by Nuitka into GoogleClassHelp.exe,
so:

- no readable ``credentials.json`` is shipped next to the executable;
- the config is loaded at runtime into memory only;
- the plaintext file never exists on the user's machine.

SECURITY NOTE (review §2.5): base64 is encoding, not encryption. The blob is
inside the executable and anyone who looks can recover it — that is inherent
to any installed desktop OAuth client. The earlier XOR-with-a-random-key
version only created an illusion of cryptography (the key shipped in the
same file), so it was removed; this file states what it really is.

If the client config must be genuinely protected, do not embed it at all:
ship without secrets and let the user drop ``credentials.json`` into the
data dir on first run (the gcloud / gh CLI model). ``auth._client_config``
reads ``GC_DASHBOARD_CREDENTIALS`` first, so that path already works.

Usage (usually invoked by build.bat):

    python build_secrets.py

Never commit ``embedded_secrets.py`` (it is git-ignored).
"""

import base64
import json
import sys
from pathlib import Path

from config import CREDENTIALS_FILE

OUTPUT_FILE = Path(__file__).resolve().parent / "embedded_secrets.py"

TEMPLATE = '''"""AUTO-GENERATED by build_secrets.py — do not edit, do not commit.

Contains the OAuth client configuration as a base64 blob. This is encoding,
not encryption: it keeps the plaintext credentials.json out of the shipped
build, but it is not a protection against anyone inspecting the executable
(see build_secrets.py).
"""

import base64
import json

_DATA = {data!r}


def get_client_config() -> dict:
    """Return the OAuth client configuration dict."""
    return json.loads(base64.b64decode(_DATA).decode("utf-8"))
'''


def main() -> int:
    if not CREDENTIALS_FILE.exists():
        print(f"ERROR: {CREDENTIALS_FILE} not found. Cannot embed OAuth client config.")
        return 1

    try:
        raw = json.loads(CREDENTIALS_FILE.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        print(f"ERROR: cannot read/parse {CREDENTIALS_FILE}: {exc}")
        return 1

    if "installed" not in raw:
        print(
            "ERROR: credentials.json does not look like an 'installed app' "
            "OAuth client (no top-level 'installed' key)."
        )
        return 1

    payload = json.dumps(raw, separators=(",", ":")).encode("utf-8")
    module = TEMPLATE.format(data=base64.b64encode(payload).decode("ascii"))
    OUTPUT_FILE.write_text(module, encoding="utf-8")
    print(
        f"OK: embedded OAuth client config -> {OUTPUT_FILE.name} "
        f"(base64, from {CREDENTIALS_FILE.name})"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
