"""Type stub for the build-time generated module (embedded_secrets.py).

The real module is generated by build_secrets.py before a production build
and is git-ignored. This stub only declares its interface so type checkers
can resolve the import during development.
"""

def get_client_config() -> dict: ...
