/**
 * The one place that knows the generated schema exists.
 *
 * `shared/types/<domain>.ts` files all derive their shapes from `Wire<>`;
 * keeping the derivation here means a field that changes on the backend breaks
 * `tsc` in exactly one place, and no domain file has to know that
 * `api-schema.d.ts` is machine output.
 *
 * The schema is generated by `npm run gen:api:file` (openapi-typescript over
 * the backend's OpenAPI document, produced by `tools/dump_openapi.py`). It is
 * never edited by hand: a manual mirror of a backend schema is the failure mode
 * ADR-0005 replaced.
 */

import type { components } from "../api/schema.d.ts";

export type Schemas = components["schemas"];

/**
 * Pydantic always serializes a field, even when the request schema marks it
 * optional through a default or a nullable type — the OpenAPI generator
 * therefore understates what the wire carries (`description?: string | null`).
 * `DeepRequired` restores the contract the responses actually keep, while the
 * generated interface stays the source of truth for field names and types.
 */
export type DeepRequired<T> = T extends (infer U)[]
    ? DeepRequired<U>[]
    : T extends object
      ? { [K in keyof T]-?: DeepRequired<T[K]> }
      : T;

export type Wire<K extends keyof Schemas> = DeepRequired<Schemas[K]>;

/**
 * The backend derives these labels, so the schema models them as free-form
 * strings; the UI is written against the closed set it can actually receive.
 *
 * The status union is passed in rather than imported: it belongs to the domain
 * (`assignment.ts`), and importing it here would make the wire layer depend on
 * a domain — the direction the layering forbids. Two type-only references in
 * opposite directions also resolve to a cycle, and a cycle between the schema
 * and the domain is exactly what `shared/types/` was split to prevent.
 */
export type WithStatus<T, S> = Omit<T, "status"> & { status: S };