/**
 * The admin strings, en.
 *
 * Split out of the single dictionary (PLAN §3.4): five hundred lines in one
 * file is a file nobody can navigate. `locales/en/index.ts` glues the
 * domains back together, so `useI18n` and every `t("...")` are unchanged.
 */

export const en_admin = {
  // --------------------------------------------------------------- admin
  // Only ever rendered when the backend reports is_admin=true (ADR-0035).
  "admin.title": "Administration",
  "admin.dashboardTitle": "Feedback dashboard",
  "admin.total": "Total",
  "admin.backToAdmin": "Back to administration",
  "admin.ticketListTitle": "All tickets",
  "admin.filterStatus": "Status",
  "admin.filterCategory": "Category",
  "admin.filterAny": "Any",
  "admin.searchPlaceholder": "Search subject or message…",
  "admin.search": "Search",
  "admin.clearFilters": "Clear filters",
  "admin.empty": "No tickets match these filters.",
  "admin.reporter": "Reporter",
  "admin.loadFailed": "Could not load the tickets.",
  "admin.replyTitle": "Answer",
  "admin.displayName": "Name shown to the user",
  "admin.displayNameHint": "The user sees this name; your account stays recorded as the author.",
  "admin.sendAnswer": "Send answer",
  "admin.statusChanged": "Status updated.",
  "admin.deleteTitle": "Delete this ticket permanently?",
  "admin.deleteBody": "This action cannot be undone. The ticket conversation and its attachments will be permanently deleted.",
  "admin.deleteConfirm": "Delete permanently",
  "admin.deleteCancel": "Cancel",
  "admin.deleteButton": "Delete ticket",
  "admin.deleted": "The ticket has been deleted.",
  "admin.deleteFailed": "Could not delete the ticket.",
  "admin.notAvailable": "This section is only available to administrators.",
  "admin.notAvailableHint": "Your account does not have administrator access. If that is unexpected, contact support.",
  "admin.by": "by {name}",
  // ------------------------------------------------ administrators (ADR-0036)
  // The /admin console, reachable only by its URL. Administrators are managed
  // here by the Super Admin alone; the display name is generated by the server
  // from the e-mail, which is why the form has no name field.
  "admin.adminsTitle": "Administrators",
  "admin.adminsAdd": "Add administrator",
  "admin.adminsEmail": "Email",
  "admin.adminsEmailHint": "The name shown in the list is generated from this address. They keep this access until you remove it.",
  "admin.adminsName": "Name",
  "admin.adminsAddedAt": "Date added",
  "admin.adminsActions": "Actions",
  "admin.adminsDelete": "Delete",
  "admin.adminsEmpty": "There are no administrators yet.",
  "admin.adminsEmptyHint": "Add one by e-mail. They will be able to answer and delete tickets, but not to manage other administrators.",
  "admin.adminsLoadFailed": "Could not load the administrators.",
  "admin.adminsAdded": "The administrator has been added.",
  "admin.adminsAddFailed": "Could not add the administrator.",
  "admin.adminsRemoved": "The administrator has been removed.",
  "admin.adminsDeleteFailed": "Could not remove the administrator.",
  "admin.adminsDeleteTitle": "Remove administrator?",
  "admin.adminsDeleteBody": "{email} will lose administrator access to GoogleClassHelp. This cannot be undone.",
  "admin.adminsDeleteConfirm": "Remove administrator",
  "admin.adminsDeleteCancel": "Cancel",
} as const;
