/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Status */
        get: operations["auth_status_api_auth_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Courses */
        get: operations["list_courses_api_courses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assignments */
        get: operations["list_assignments_api_assignments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Upcoming */
        get: operations["upcoming_api_assignments_upcoming_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments/overdue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overdue */
        get: operations["overdue_api_assignments_overdue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Grades */
        get: operations["grades_api_grades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calendar */
        get: operations["calendar_api_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Sync
         * @description Synchronize the calling user's cache with THEIR Google credentials.
         *
         *     §12: /api/sync must never touch another user's data. Desktop: the local
         *     owner (token.json). Hosted: the session user's oauth_tokens — sync_now
         *     resolves the cache owner and credentials from this user. Since the
         *     per-user scheduler (stage 5, §18) a manual sync only conflicts with
         *     THIS user's own running sync (background or another manual call); any
         *     other user syncs independently.
         */
        post: operations["run_sync_api_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Clear Cache */
        delete: operations["clear_cache_api_cache_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Course Detail */
        get: operations["course_detail_api_courses__course_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/coursework": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Course Coursework
         * @description Coursework of one course: all of it for a teacher, own work for a student.
         */
        get: operations["course_coursework_api_courses__course_id__coursework_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Course Students */
        get: operations["course_students_api_courses__course_id__students_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Course Grades
         * @description Spreadsheet-style grade matrix: every student × every assignment.
         */
        get: operations["course_grades_api_courses__course_id__grades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/coursework/{coursework_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Coursework Detail
         * @description Full assignment page: metadata, materials and the submission table.
         */
        get: operations["coursework_detail_api_courses__course_id__coursework__coursework_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/coursework/{coursework_id}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coursework Submissions */
        get: operations["coursework_submissions_api_courses__course_id__coursework__coursework_id__submissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/students/{student_id}/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Student Grades
         * @description One student's coursework, submission state and grade for a course.
         */
        get: operations["student_grades_api_courses__course_id__students__student_id__grades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssignmentDetailOut */
        AssignmentDetailOut: {
            /** Id */
            id: string;
            /** Course Id */
            course_id: string;
            /** Course Name */
            course_name: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Due At */
            due_at?: string | null;
            /** Max Points */
            max_points?: number | null;
            /** Work Type */
            work_type?: string | null;
            /** State */
            state?: string | null;
            /** Alternate Link */
            alternate_link?: string | null;
            /** Materials */
            materials?: components["schemas"]["MaterialOut"][];
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Submission State */
            submission_state?: string | null;
            /**
             * Submitted
             * @default false
             */
            submitted: boolean;
            /**
             * Graded
             * @default false
             */
            graded: boolean;
            /** Points */
            points?: number | null;
            /**
             * Late
             * @default false
             */
            late: boolean;
            /**
             * Is Overdue
             * @default false
             */
            is_overdue: boolean;
            /**
             * Priority
             * @default low
             */
            priority: string;
            /**
             * Role
             * @default STUDENT
             */
            role: string;
            /**
             * Student Count
             * @default 0
             */
            student_count: number;
            /**
             * Submission Count
             * @default 0
             */
            submission_count: number;
            /**
             * Graded Count
             * @default 0
             */
            graded_count: number;
            /** Average Percent */
            average_percent?: number | null;
            /** Submissions */
            submissions?: components["schemas"]["SubmissionOut"][];
            /** Status Counts */
            status_counts?: {
                [key: string]: number;
            };
        };
        /** AssignmentOut */
        AssignmentOut: {
            /** Id */
            id: string;
            /** Course Id */
            course_id: string;
            /** Course Name */
            course_name: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Due At */
            due_at?: string | null;
            /** Max Points */
            max_points?: number | null;
            /** Work Type */
            work_type?: string | null;
            /** State */
            state?: string | null;
            /** Alternate Link */
            alternate_link?: string | null;
            /** Materials */
            materials?: components["schemas"]["MaterialOut"][];
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Submission State */
            submission_state?: string | null;
            /**
             * Submitted
             * @default false
             */
            submitted: boolean;
            /**
             * Graded
             * @default false
             */
            graded: boolean;
            /** Points */
            points?: number | null;
            /**
             * Late
             * @default false
             */
            late: boolean;
            /**
             * Is Overdue
             * @default false
             */
            is_overdue: boolean;
            /**
             * Priority
             * @default low
             */
            priority: string;
            /**
             * Role
             * @default STUDENT
             */
            role: string;
            /**
             * Student Count
             * @default 0
             */
            student_count: number;
            /**
             * Submission Count
             * @default 0
             */
            submission_count: number;
            /**
             * Graded Count
             * @default 0
             */
            graded_count: number;
            /** Average Percent */
            average_percent?: number | null;
        };
        /** AuthStatus */
        AuthStatus: {
            /** Authenticated */
            authenticated: boolean;
            /**
             * Login In Progress
             * @default false
             */
            login_in_progress: boolean;
            /** Error */
            error?: string | null;
            /** Auth Url */
            auth_url?: string | null;
            /** User Name */
            user_name?: string | null;
            /** User Email */
            user_email?: string | null;
        };
        /** CourseDetailOut */
        CourseDetailOut: {
            course: components["schemas"]["CourseOut"];
            /**
             * Role
             * @default STUDENT
             */
            role: string;
            /** Students */
            students?: components["schemas"]["StudentOut"][];
            /** Last Sync */
            last_sync?: string | null;
        };
        /** CourseGrades */
        CourseGrades: {
            /** Course Id */
            course_id: string;
            /** Course Name */
            course_name: string;
            /** Average */
            average?: number | null;
            /** Items */
            items?: components["schemas"]["GradeItem"][];
        };
        /** CourseOut */
        CourseOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Section */
            section?: string | null;
            /** Room */
            room?: string | null;
            /** Course State */
            course_state?: string | null;
            /** Teachers */
            teachers?: string[];
            /**
             * Role
             * @default STUDENT
             */
            role: string;
            /**
             * Student Count
             * @default 0
             */
            student_count: number;
            /**
             * Total Assignments
             * @default 0
             */
            total_assignments: number;
            /**
             * Todo Count
             * @default 0
             */
            todo_count: number;
            /**
             * Overdue Count
             * @default 0
             */
            overdue_count: number;
            /**
             * Graded Count
             * @default 0
             */
            graded_count: number;
            /** Average Grade */
            average_grade?: number | null;
        };
        /** GradeColumn */
        GradeColumn: {
            /** Assignment Id */
            assignment_id: string;
            /** Title */
            title: string;
            /** Max Points */
            max_points?: number | null;
            /** Due At */
            due_at?: string | null;
        };
        /** GradeItem */
        GradeItem: {
            /** Assignment Id */
            assignment_id: string;
            /** Title */
            title: string;
            /** Points */
            points?: number | null;
            /** Max Points */
            max_points?: number | null;
            /** Percent */
            percent?: number | null;
            /** Graded At */
            graded_at?: string | null;
            /** Due At */
            due_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MaterialOut */
        MaterialOut: {
            /** Type */
            type?: string | null;
            /** Title */
            title?: string | null;
            /** Url */
            url?: string | null;
        };
        /** StudentGradeItem */
        StudentGradeItem: {
            /** Assignment Id */
            assignment_id: string;
            /** Title */
            title: string;
            /** Due At */
            due_at?: string | null;
            /** Max Points */
            max_points?: number | null;
            /** Submission State */
            submission_state?: string | null;
            /**
             * Status
             * @default not_submitted
             */
            status: string;
            /**
             * Submitted
             * @default false
             */
            submitted: boolean;
            /**
             * Returned
             * @default false
             */
            returned: boolean;
            /**
             * Graded
             * @default false
             */
            graded: boolean;
            /**
             * Late
             * @default false
             */
            late: boolean;
            /** Points */
            points?: number | null;
            /** Percent */
            percent?: number | null;
            /** Submitted At */
            submitted_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Attachments */
            attachments?: components["schemas"]["MaterialOut"][];
            /** Alternate Link */
            alternate_link?: string | null;
        };
        /** StudentGradeRow */
        StudentGradeRow: {
            student: components["schemas"]["StudentOut"];
            /** Cells */
            cells?: components["schemas"]["SubmissionCell"][];
            /** Average Percent */
            average_percent?: number | null;
        };
        /** StudentGradesOut */
        StudentGradesOut: {
            /** Course Id */
            course_id: string;
            /** Course Name */
            course_name: string;
            student: components["schemas"]["StudentOut"];
            /** Average Percent */
            average_percent?: number | null;
            /** Items */
            items?: components["schemas"]["StudentGradeItem"][];
            /** Last Sync */
            last_sync?: string | null;
        };
        /** StudentOut */
        StudentOut: {
            /** Id */
            id: string;
            /**
             * Full Name
             * @default
             */
            full_name: string;
            /** Email */
            email?: string | null;
            /** Photo Url */
            photo_url?: string | null;
        };
        /** SubmissionCell */
        SubmissionCell: {
            /** Coursework Id */
            coursework_id: string;
            /**
             * Status
             * @default not_submitted
             */
            status: string;
            /**
             * Submitted
             * @default false
             */
            submitted: boolean;
            /**
             * Returned
             * @default false
             */
            returned: boolean;
            /**
             * Graded
             * @default false
             */
            graded: boolean;
            /**
             * Late
             * @default false
             */
            late: boolean;
            /** Points */
            points?: number | null;
            /** Max Points */
            max_points?: number | null;
            /** Percent */
            percent?: number | null;
            /** Submitted At */
            submitted_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * SubmissionOut
         * @description One student's submission for a coursework item (teacher view).
         *
         *     `status` collapses the API state + grade into one label
         *     (not_submitted | turned_in | returned | graded); the booleans stay
         *     available for filtering. A missing grade is never rendered as 0.
         */
        SubmissionOut: {
            /** Student Id */
            student_id: string;
            /**
             * Student Name
             * @default
             */
            student_name: string;
            /** Coursework Id */
            coursework_id: string;
            /** Submission State */
            submission_state?: string | null;
            /**
             * Status
             * @default not_submitted
             */
            status: string;
            /**
             * Submitted
             * @default false
             */
            submitted: boolean;
            /**
             * Returned
             * @default false
             */
            returned: boolean;
            /**
             * Graded
             * @default false
             */
            graded: boolean;
            /**
             * Late
             * @default false
             */
            late: boolean;
            /** Points */
            points?: number | null;
            /** Max Points */
            max_points?: number | null;
            /** Percent */
            percent?: number | null;
            /** Submitted At */
            submitted_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Attachments */
            attachments?: components["schemas"]["MaterialOut"][];
        };
        /** SyncResult */
        SyncResult: {
            /** Ok */
            ok: boolean;
            /** Last Sync */
            last_sync?: string | null;
            /**
             * Courses
             * @default 0
             */
            courses: number;
            /**
             * Assignments
             * @default 0
             */
            assignments: number;
            /** Error */
            error?: string | null;
        };
        /** SyncStatus */
        SyncStatus: {
            /** Authenticated */
            authenticated: boolean;
            /** User Name */
            user_name?: string | null;
            /** User Email */
            user_email?: string | null;
            /** Last Sync */
            last_sync?: string | null;
            /** Last Sync Error */
            last_sync_error?: string | null;
            /**
             * Syncing
             * @default false
             */
            syncing: boolean;
            /**
             * Sync Status
             * @default pending
             */
            sync_status: string;
            /** Last Sync Started At */
            last_sync_started_at?: string | null;
            /** Last Sync Finished At */
            last_sync_finished_at?: string | null;
            /**
             * Total Assignments
             * @default 0
             */
            total_assignments: number;
            /**
             * Completed
             * @default 0
             */
            completed: number;
            /**
             * Missing
             * @default 0
             */
            missing: number;
            /**
             * Overdue
             * @default 0
             */
            overdue: number;
            /**
             * Due Today
             * @default 0
             */
            due_today: number;
            /** Average Grade */
            average_grade?: number | null;
        };
        /** TeacherGradesOut */
        TeacherGradesOut: {
            /** Course Id */
            course_id: string;
            /** Course Name */
            course_name: string;
            /**
             * Role
             * @default TEACHER
             */
            role: string;
            /** Assignments */
            assignments?: components["schemas"]["GradeColumn"][];
            /** Rows */
            rows?: components["schemas"]["StudentGradeRow"][];
            /** Class Average */
            class_average?: number | null;
            /** Last Sync */
            last_sync?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_status_api_auth_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    list_courses_api_courses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseOut"][];
                };
            };
        };
    };
    list_assignments_api_assignments_get: {
        parameters: {
            query?: {
                course_id?: string | null;
                search?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upcoming_api_assignments_upcoming_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overdue_api_assignments_overdue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentOut"][];
                };
            };
        };
    };
    grades_api_grades_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseGrades"][];
                };
            };
        };
    };
    calendar_api_calendar_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatus"];
                };
            };
        };
    };
    run_sync_api_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"];
                };
            };
        };
    };
    clear_cache_api_cache_delete: {
        parameters: {
            query?: {
                confirm?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    course_detail_api_courses__course_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    course_coursework_api_courses__course_id__coursework_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    course_students_api_courses__course_id__students_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    course_grades_api_courses__course_id__grades_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherGradesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coursework_detail_api_courses__course_id__coursework__coursework_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                coursework_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coursework_submissions_api_courses__course_id__coursework__coursework_id__submissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                coursework_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    student_grades_api_courses__course_id__students__student_id__grades_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentGradesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
