/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Status */
        get: operations["auth_status_api_auth_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Identity of the signed-in user (§23/§24).
         *
         *     Same identity source as ``/api/auth/status``: the validated session
         *     user in hosted mode, the desktop local owner (with the Google profile
         *     resolved and cached per user) in desktop mode. A request without a
         *     valid application session is rejected earlier with 401 (hosted session
         *     gate / dependency); this handler never sees an anonymous caller.
         */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        /**
         * Delete Own Account
         * @description Delete everything stored for the CALLER (§44).
         *
         *     The explicit "delete my account" path: sessions, OAuth credentials,
         *     sync state and the whole Classroom cache of this user are removed, and
         *     the local ``users`` row goes with them. Other users' rows are never
         *     touched — there is deliberately no global variant of this operation.
         *
         *     Desktop builds have no server-side account (single local user, data in
         *     ``%LOCALAPPDATA%``): the endpoint is hosted-only and answers 400 there
         *     with a pointer to ``DELETE /api/cache`` + logout.
         */
        delete: operations["delete_own_account_api_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Courses */
        get: operations["list_courses_api_courses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assignments */
        get: operations["list_assignments_api_assignments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Upcoming */
        get: operations["upcoming_api_assignments_upcoming_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments/overdue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overdue */
        get: operations["overdue_api_assignments_overdue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Grades */
        get: operations["grades_api_grades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calendar */
        get: operations["calendar_api_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Sync
         * @description Queue (hosted) or run (desktop) a sync of the calling user's cache.
         *
         *     §12: /api/sync must never touch another user's data. Desktop: the local
         *     owner (token.json) — sync runs inline as before. Hosted: the session
         *     user's oauth_tokens — the request only flags ``sync_requested`` and
         *     answers ``{"ok": True, "queued": True, "status": "queued"}`` immediately;
         *     the worker container performs the actual Classroom fan-out (DDoS plan
         *     §9: never run the full sync inside the HTTP request).
         *
         *     Hosted conflict mapping: a sync already in flight for THIS user → 409;
         *     a manual request inside the per-user cooldown → 429 + Retry-After; the
         *     background scheduler bypasses the cooldown. Other users sync
         *     independently. Rate-limit buckets (§39) stay in middleware.
         *
         *     ``restart=true`` (ADR-0032) is the dashboard's answer to "this sync is
         *     stuck". It is the ONE case where an in-flight sync does not answer 409: a
         *     claim older than ``SYNC_STUCK_SECONDS`` is released and a new one queued.
         *     A younger claim still answers 409 — a long but progressing Classroom
         *     import must never be interrupted, and the cooldown is skipped only because
         *     the abandoned claim is by definition older than it.
         */
        post: operations["run_sync_api_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Clear Cache */
        delete: operations["clear_cache_api_cache_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Clear Own Cache
         * @description Explicit alias of ``DELETE /api/cache`` (stage 9, §66).
         *
         *     Same handler shape, same per-user scope, same ``confirm=true`` gate —
         *     the path only says what the code already does: delete the CALLER's
         *     cache, never anyone else's. Kept side by side with ``/api/cache`` so
         *     existing desktop clients keep working while new clients can use the
         *     unambiguous name.
         */
        delete: operations["clear_own_cache_api_me_cache_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Disconnect Google Account
         * @description Disconnect the caller's Google account, keep the local account (§44).
         *
         *     Removes the stored OAuth credentials and resets the caller's sync state
         *     of THIS user only; the application session stays valid (the caller
         *     stays signed in to the dashboard and its cached data remains visible,
         *     with its last-sync timestamp). ``confirm=true`` is required because the
         *     action forces a fresh consent screen on the next sync.
         */
        delete: operations["disconnect_google_account_api_me_google_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Course Detail */
        get: operations["course_detail_api_courses__course_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/coursework": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Course Coursework
         * @description Coursework of one course: all of it for a teacher, own work for a student.
         */
        get: operations["course_coursework_api_courses__course_id__coursework_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Course Students */
        get: operations["course_students_api_courses__course_id__students_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Course Grades
         * @description Spreadsheet-style grade matrix: every student × every assignment.
         */
        get: operations["course_grades_api_courses__course_id__grades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/coursework/{coursework_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Coursework Detail
         * @description Full assignment page: metadata, materials and the submission table.
         */
        get: operations["coursework_detail_api_courses__course_id__coursework__coursework_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/coursework/{coursework_id}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coursework Submissions */
        get: operations["coursework_submissions_api_courses__course_id__coursework__coursework_id__submissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/students/{student_id}/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Student Grades
         * @description One student's coursework, submission state and grade for a course.
         */
        get: operations["student_grades_api_courses__course_id__students__student_id__grades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List My Tickets
         * @description The caller's OWN tickets, newest activity first.
         *
         *     Sorted by ``updated_at`` (bumped by every message), not by creation date: a
         *     ticket somebody just answered is the one being looked for.
         */
        get: operations["list_my_tickets_api_feedback_tickets_get"];
        put?: never;
        /**
         * Create Ticket
         * @description Open a ticket: category, subject, the first Markdown message, files.
         *
         *     201 with the created ticket and its conversation, so the UI can navigate
         *     straight to the thread. The rate limit is checked BEFORE the body is read,
         *     so a spam loop never uploads a megabyte.
         */
        post: operations["create_ticket_api_feedback_tickets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Ticket
         * @description One own ticket with its whole conversation, or 404.
         */
        get: operations["get_my_ticket_api_feedback_tickets__ticket_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback/tickets/{ticket_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reply To Ticket
         * @description Reply to an own ticket.
         *
         *     The body carries ``body_markdown`` only. ``author_type``,
         *     ``author_user_id``, ``author_email`` and ``display_name`` are not part of the
         *     model, so sending them changes nothing — a user cannot post under somebody
         *     else's name (ADR-0035).
         *
         *     Replying to a ``resolved`` ticket reopens it (``in_progress``), which the
         *     UI shows immediately.
         */
        post: operations["reply_to_ticket_api_feedback_tickets__ticket_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback/attachments/{attachment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Attachment
         * @description Download an attachment of a ticket the caller OWNS (or any, as an admin).
         *
         *     The ownership check is a single joined statement: the attachment's ticket
         *     must belong to the caller. Somebody else's file is 404 — indistinguishable
         *     from a missing one. Administrators may read any attachment, because support
         *     has to see what was sent; the fallback path is still 404 for a missing row.
         */
        get: operations["download_attachment_api_feedback_attachments__attachment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/feedback/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tickets
         * @description Every ticket, filtered by status/category/search, paginated.
         *
         *     ``q`` matches a subject or a message body as a substring (case-insensitive
         *     through ``ILIKE``; SQLite's ``like`` is case-insensitive for ASCII, which is
         *     what the tests assert). The filters are ANDed and the ordering is the same
         *     "newest activity first" as everywhere else, so the list stays stable while
         *     somebody works on it.
         */
        get: operations["list_tickets_api_admin_feedback_tickets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/feedback/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Feedback Stats
         * @description Dashboard counters: total and the per-status breakdown.
         *
         *     One grouped query (feedback_service.counts_by_status) rather than four
         *     counts, and no ordering — the dashboard wants numbers, not rows.
         */
        get: operations["feedback_stats_api_admin_feedback_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/feedback/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Ticket
         * @description Any ticket with its full conversation and the real author identities.
         *
         *     Not filtered by the caller — an administrator is supposed to see every
         *     ticket. The dependency above already answered 401/403.
         */
        get: operations["read_ticket_api_admin_feedback_tickets__ticket_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Ticket
         * @description Delete a ticket permanently, with its conversation and its files.
         *
         *     Real deletion, no ``deleted_at`` and no restore (ADR-0035): the row goes,
         *     ``ON DELETE CASCADE`` takes the messages and attachment rows with it, and the
         *     files are unlinked from the volume. 204 on success, 404 for a ticket that
         *     does not exist — afterwards the id answers 404 for the owner as well, and
         *     the ticket is gone from a fresh list.
         *
         *     A file that cannot be unlinked does NOT fail the request: the row deletion
         *     is the contract, and the filesystem cleanup is best effort.
         */
        delete: operations["delete_ticket_api_admin_feedback_tickets__ticket_id__delete"];
        options?: never;
        head?: never;
        /**
         * Set Status
         * @description Change the ticket status — and ONLY the status.
         *
         *     The body is ``{"status": "resolved"}``; anything else is ignored by the
         *     model, so this endpoint cannot become a way to rewrite a message, an author
         *     or an owner. An unknown status is 422 (the closed set).
         */
        patch: operations["set_status_api_admin_feedback_tickets__ticket_id__patch"];
        trace?: never;
    };
    "/api/admin/feedback/tickets/{ticket_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reply To Ticket
         * @description Answer a ticket under a chosen public display name.
         *
         *     The stored identity is split in two, and this is the whole point of the
         *     feature:
         *
         *     - ``author_user_id`` / ``author_email`` = the AUTHENTICATED administrator,
         *       taken from the session — never from the request, so the audit trail stays
         *       correct;
         *     - ``display_name`` = the public label the ticket owner sees (default
         *       ``GoogleClassHelp Support``, capped at 100 characters). Two administrators
         *       may therefore answer under different names while both are recorded
         *       correctly internally.
         */
        post: operations["reply_to_ticket_api_admin_feedback_tickets__ticket_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness check (migration stage 10, §58 / DDoS plan §24).
         *
         *     Verifies that the database connection pool and engine are operational
         *     without leaking infrastructure details, environment variables, or credentials.
         *     Returns 200 {"ok": True, "db": "up"} or 503 {"ok": False, "db": "down"}.
         */
        get: operations["ready_api_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminMessageOut
         * @description A message with the internal identity an administrator may read.
         */
        AdminMessageOut: {
            /** Id */
            id: number;
            /** Author Type */
            author_type: string;
            /** Display Name */
            display_name: string;
            /** Body Markdown */
            body_markdown: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Attachments */
            attachments?: components["schemas"]["AttachmentOut"][];
            /** Author User Id */
            author_user_id: number;
            /** Author Email */
            author_email?: string | null;
        };
        /**
         * AdminTicketDetailOut
         * @description Any ticket with the full conversation and the real author identities.
         */
        AdminTicketDetailOut: {
            /** Id */
            id: number;
            /** Category */
            category: string;
            /** Subject */
            subject: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** User Id */
            user_id: number;
            /** User Name */
            user_name?: string | null;
            /** User Email */
            user_email?: string | null;
            /** Messages */
            messages?: components["schemas"]["AdminMessageOut"][];
        };
        /**
         * AdminTicketListOut
         * @description A page of the admin list plus the total for the pagination control.
         */
        AdminTicketListOut: {
            /** Items */
            items?: components["schemas"]["AdminTicketOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * AdminTicketOut
         * @description A ticket row for the admin list, with its owner.
         */
        AdminTicketOut: {
            /** Id */
            id: number;
            /** Category */
            category: string;
            /** Subject */
            subject: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
            /** User Id */
            user_id: number;
            /** User Name */
            user_name?: string | null;
            /** User Email */
            user_email?: string | null;
        };
        /** AssignmentDetailOut */
        AssignmentDetailOut: {
            /** Id */
            id: string;
            /** Course Id */
            course_id: string;
            /** Course Name */
            course_name: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Due At */
            due_at?: string | null;
            /** Max Points */
            max_points?: number | null;
            /** Work Type */
            work_type?: string | null;
            /** State */
            state?: string | null;
            /** Alternate Link */
            alternate_link?: string | null;
            /** Materials */
            materials?: components["schemas"]["MaterialOut"][];
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Submission State */
            submission_state?: string | null;
            /**
             * Submitted
             * @default false
             */
            submitted: boolean;
            /**
             * Graded
             * @default false
             */
            graded: boolean;
            /** Points */
            points?: number | null;
            /**
             * Late
             * @default false
             */
            late: boolean;
            /**
             * Is Overdue
             * @default false
             */
            is_overdue: boolean;
            /**
             * Priority
             * @default low
             */
            priority: string;
            /**
             * Role
             * @default STUDENT
             */
            role: string;
            /**
             * Student Count
             * @default 0
             */
            student_count: number;
            /**
             * Submission Count
             * @default 0
             */
            submission_count: number;
            /**
             * Graded Count
             * @default 0
             */
            graded_count: number;
            /** Average Percent */
            average_percent?: number | null;
            /** Submissions */
            submissions?: components["schemas"]["SubmissionOut"][];
            /** Status Counts */
            status_counts?: {
                [key: string]: number;
            };
        };
        /** AssignmentOut */
        AssignmentOut: {
            /** Id */
            id: string;
            /** Course Id */
            course_id: string;
            /** Course Name */
            course_name: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Due At */
            due_at?: string | null;
            /** Max Points */
            max_points?: number | null;
            /** Work Type */
            work_type?: string | null;
            /** State */
            state?: string | null;
            /** Alternate Link */
            alternate_link?: string | null;
            /** Materials */
            materials?: components["schemas"]["MaterialOut"][];
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Submission State */
            submission_state?: string | null;
            /**
             * Submitted
             * @default false
             */
            submitted: boolean;
            /**
             * Graded
             * @default false
             */
            graded: boolean;
            /** Points */
            points?: number | null;
            /**
             * Late
             * @default false
             */
            late: boolean;
            /**
             * Is Overdue
             * @default false
             */
            is_overdue: boolean;
            /**
             * Priority
             * @default low
             */
            priority: string;
            /**
             * Role
             * @default STUDENT
             */
            role: string;
            /**
             * Student Count
             * @default 0
             */
            student_count: number;
            /**
             * Submission Count
             * @default 0
             */
            submission_count: number;
            /**
             * Graded Count
             * @default 0
             */
            graded_count: number;
            /** Average Percent */
            average_percent?: number | null;
        };
        /**
         * AttachmentOut
         * @description Metadata of one uploaded file; the bytes come from the download endpoint.
         */
        AttachmentOut: {
            /** Id */
            id: number;
            /** Original Name */
            original_name: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * AuthStatus
         * @description Auth state of THIS browser's application session (§24).
         *
         *     ``user`` is the only identity shape (migration stage 7, §26): the flat
         *     ``user_name``/``user_email`` mirrors were dropped once the frontend
         *     switched over. ``auth_url``/``login_in_progress`` remain because the
         *     desktop loopback flow still publishes its single-use consent URL.
         */
        AuthStatus: {
            /** Authenticated */
            authenticated: boolean;
            /**
             * Login In Progress
             * @default false
             */
            login_in_progress: boolean;
            /** Error */
            error?: string | null;
            /** Auth Url */
            auth_url?: string | null;
            user?: components["schemas"]["UserOut"] | null;
        };
        /** CourseDetailOut */
        CourseDetailOut: {
            course: components["schemas"]["CourseOut"];
            /**
             * Role
             * @default STUDENT
             */
            role: string;
            /** Students */
            students?: components["schemas"]["StudentOut"][];
            /** Last Sync */
            last_sync?: string | null;
        };
        /** CourseGrades */
        CourseGrades: {
            /** Course Id */
            course_id: string;
            /** Course Name */
            course_name: string;
            /** Average */
            average?: number | null;
            /** Items */
            items?: components["schemas"]["GradeItem"][];
        };
        /** CourseOut */
        CourseOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Section */
            section?: string | null;
            /** Room */
            room?: string | null;
            /** Course State */
            course_state?: string | null;
            /** Teachers */
            teachers?: string[];
            /**
             * Role
             * @default STUDENT
             */
            role: string;
            /**
             * Student Count
             * @default 0
             */
            student_count: number;
            /**
             * Total Assignments
             * @default 0
             */
            total_assignments: number;
            /**
             * Todo Count
             * @default 0
             */
            todo_count: number;
            /**
             * Overdue Count
             * @default 0
             */
            overdue_count: number;
            /**
             * Graded Count
             * @default 0
             */
            graded_count: number;
            /** Average Grade */
            average_grade?: number | null;
        };
        /**
         * FeedbackStatsOut
         * @description Dashboard counters: the totals per status plus the closed/open split.
         */
        FeedbackStatsOut: {
            /** Total */
            total: number;
            /** New */
            new: number;
            /** In Progress */
            in_progress: number;
            /** Resolved */
            resolved: number;
        };
        /** GradeColumn */
        GradeColumn: {
            /** Assignment Id */
            assignment_id: string;
            /** Title */
            title: string;
            /** Max Points */
            max_points?: number | null;
            /** Due At */
            due_at?: string | null;
        };
        /** GradeItem */
        GradeItem: {
            /** Assignment Id */
            assignment_id: string;
            /** Title */
            title: string;
            /** Points */
            points?: number | null;
            /** Max Points */
            max_points?: number | null;
            /** Percent */
            percent?: number | null;
            /** Graded At */
            graded_at?: string | null;
            /** Due At */
            due_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MaterialOut */
        MaterialOut: {
            /** Type */
            type?: string | null;
            /** Title */
            title?: string | null;
            /** Url */
            url?: string | null;
        };
        /**
         * MessageOut
         * @description One conversation message as a regular user may see it.
         *
         *     No ``author_user_id`` and no ``author_email``: a regular user sees the
         *     PUBLIC byline of the conversation and nothing else.
         */
        MessageOut: {
            /** Id */
            id: number;
            /** Author Type */
            author_type: string;
            /** Display Name */
            display_name: string;
            /** Body Markdown */
            body_markdown: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Attachments */
            attachments?: components["schemas"]["AttachmentOut"][];
        };
        /** StudentGradeItem */
        StudentGradeItem: {
            /** Assignment Id */
            assignment_id: string;
            /** Title */
            title: string;
            /** Due At */
            due_at?: string | null;
            /** Max Points */
            max_points?: number | null;
            /** Submission State */
            submission_state?: string | null;
            /**
             * Status
             * @default not_submitted
             */
            status: string;
            /**
             * Submitted
             * @default false
             */
            submitted: boolean;
            /**
             * Returned
             * @default false
             */
            returned: boolean;
            /**
             * Graded
             * @default false
             */
            graded: boolean;
            /**
             * Late
             * @default false
             */
            late: boolean;
            /** Points */
            points?: number | null;
            /** Percent */
            percent?: number | null;
            /** Submitted At */
            submitted_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Attachments */
            attachments?: components["schemas"]["MaterialOut"][];
            /** Alternate Link */
            alternate_link?: string | null;
        };
        /** StudentGradeRow */
        StudentGradeRow: {
            student: components["schemas"]["StudentOut"];
            /** Cells */
            cells?: components["schemas"]["SubmissionCell"][];
            /** Average Percent */
            average_percent?: number | null;
        };
        /** StudentGradesOut */
        StudentGradesOut: {
            /** Course Id */
            course_id: string;
            /** Course Name */
            course_name: string;
            student: components["schemas"]["StudentOut"];
            /** Average Percent */
            average_percent?: number | null;
            /** Items */
            items?: components["schemas"]["StudentGradeItem"][];
            /** Last Sync */
            last_sync?: string | null;
        };
        /** StudentOut */
        StudentOut: {
            /** Id */
            id: string;
            /**
             * Full Name
             * @default
             */
            full_name: string;
            /** Email */
            email?: string | null;
            /** Photo Url */
            photo_url?: string | null;
        };
        /** SubmissionCell */
        SubmissionCell: {
            /** Coursework Id */
            coursework_id: string;
            /**
             * Status
             * @default not_submitted
             */
            status: string;
            /**
             * Submitted
             * @default false
             */
            submitted: boolean;
            /**
             * Returned
             * @default false
             */
            returned: boolean;
            /**
             * Graded
             * @default false
             */
            graded: boolean;
            /**
             * Late
             * @default false
             */
            late: boolean;
            /** Points */
            points?: number | null;
            /** Max Points */
            max_points?: number | null;
            /** Percent */
            percent?: number | null;
            /** Submitted At */
            submitted_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * SubmissionOut
         * @description One student's submission for a coursework item (teacher view).
         *
         *     `status` collapses the API state + grade into one label
         *     (not_submitted | turned_in | returned | graded); the booleans stay
         *     available for filtering. A missing grade is never rendered as 0.
         */
        SubmissionOut: {
            /** Student Id */
            student_id: string;
            /**
             * Student Name
             * @default
             */
            student_name: string;
            /** Coursework Id */
            coursework_id: string;
            /** Submission State */
            submission_state?: string | null;
            /**
             * Status
             * @default not_submitted
             */
            status: string;
            /**
             * Submitted
             * @default false
             */
            submitted: boolean;
            /**
             * Returned
             * @default false
             */
            returned: boolean;
            /**
             * Graded
             * @default false
             */
            graded: boolean;
            /**
             * Late
             * @default false
             */
            late: boolean;
            /** Points */
            points?: number | null;
            /** Max Points */
            max_points?: number | null;
            /** Percent */
            percent?: number | null;
            /** Submitted At */
            submitted_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Attachments */
            attachments?: components["schemas"]["MaterialOut"][];
        };
        /** SyncResult */
        SyncResult: {
            /** Ok */
            ok: boolean;
            /** Last Sync */
            last_sync?: string | null;
            /**
             * Courses
             * @default 0
             */
            courses: number;
            /**
             * Assignments
             * @default 0
             */
            assignments: number;
            /** Error */
            error?: string | null;
            /**
             * Queued
             * @default false
             */
            queued: boolean;
            /** Status */
            status?: string | null;
            /**
             * Restarted
             * @default false
             */
            restarted: boolean;
        };
        /** SyncStatus */
        SyncStatus: {
            /** Authenticated */
            authenticated: boolean;
            /** Last Sync */
            last_sync?: string | null;
            /** Last Sync Error */
            last_sync_error?: string | null;
            /**
             * Syncing
             * @default false
             */
            syncing: boolean;
            /**
             * Sync Status
             * @default pending
             */
            sync_status: string;
            /** Last Sync Started At */
            last_sync_started_at?: string | null;
            /** Last Sync Finished At */
            last_sync_finished_at?: string | null;
            /**
             * Sync Stuck After Seconds
             * @default 300
             */
            sync_stuck_after_seconds: number;
            /**
             * Total Assignments
             * @default 0
             */
            total_assignments: number;
            /**
             * Completed
             * @default 0
             */
            completed: number;
            /**
             * Missing
             * @default 0
             */
            missing: number;
            /**
             * Overdue
             * @default 0
             */
            overdue: number;
            /**
             * Due Today
             * @default 0
             */
            due_today: number;
            /** Average Grade */
            average_grade?: number | null;
        };
        /** TeacherGradesOut */
        TeacherGradesOut: {
            /** Course Id */
            course_id: string;
            /** Course Name */
            course_name: string;
            /**
             * Role
             * @default TEACHER
             */
            role: string;
            /** Assignments */
            assignments?: components["schemas"]["GradeColumn"][];
            /** Rows */
            rows?: components["schemas"]["StudentGradeRow"][];
            /** Class Average */
            class_average?: number | null;
            /** Last Sync */
            last_sync?: string | null;
        };
        /**
         * TicketDetailOut
         * @description One ticket with its whole conversation, as its OWNER sees it.
         */
        TicketDetailOut: {
            /** Id */
            id: number;
            /** Category */
            category: string;
            /** Subject */
            subject: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Messages */
            messages?: components["schemas"]["MessageOut"][];
        };
        /**
         * TicketOut
         * @description One ticket in a list (no conversation).
         */
        TicketOut: {
            /** Id */
            id: number;
            /** Category */
            category: string;
            /** Subject */
            subject: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
        };
        /**
         * UserOut
         * @description Identity of the authenticated user (migration stage 6, §24).
         *
         *     Exactly the fields the frontend needs to render "signed in as", plus the
         *     single ``is_admin`` boolean of ADR-0035. That flag is computed by the
         *     backend from the same membership test ``admin_auth.require_admin`` enforces,
         *     so the UI can hide the admin surface — while the API answers 403 regardless
         *     of what the UI decided. The administrator ADDRESSES are never part of this
         *     model, so they cannot reach the browser bundle.
         */
        UserOut: {
            /** Id */
            id: number;
            /** Name */
            name?: string | null;
            /** Email */
            email?: string | null;
            /**
             * Is Admin
             * @default false
             */
            is_admin: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_status_api_auth_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    delete_own_account_api_me_delete: {
        parameters: {
            query?: {
                confirm?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    list_courses_api_courses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseOut"][];
                };
            };
        };
    };
    list_assignments_api_assignments_get: {
        parameters: {
            query?: {
                course_id?: string | null;
                search?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upcoming_api_assignments_upcoming_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overdue_api_assignments_overdue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentOut"][];
                };
            };
        };
    };
    grades_api_grades_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseGrades"][];
                };
            };
        };
    };
    calendar_api_calendar_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatus"];
                };
            };
        };
    };
    run_sync_api_sync_post: {
        parameters: {
            query?: {
                /** @description Abandon a stuck sync and start a new one (ADR-0032). */
                restart?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_cache_api_cache_delete: {
        parameters: {
            query?: {
                confirm?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_own_cache_api_me_cache_delete: {
        parameters: {
            query?: {
                confirm?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_google_account_api_me_google_delete: {
        parameters: {
            query?: {
                confirm?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    course_detail_api_courses__course_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    course_coursework_api_courses__course_id__coursework_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    course_students_api_courses__course_id__students_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    course_grades_api_courses__course_id__grades_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherGradesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coursework_detail_api_courses__course_id__coursework__coursework_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                coursework_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coursework_submissions_api_courses__course_id__coursework__coursework_id__submissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                coursework_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    student_grades_api_courses__course_id__students__student_id__grades_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentGradesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_tickets_api_feedback_tickets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"][];
                };
            };
        };
    };
    create_ticket_api_feedback_tickets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetailOut"];
                };
            };
        };
    };
    get_my_ticket_api_feedback_tickets__ticket_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reply_to_ticket_api_feedback_tickets__ticket_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_attachment_api_feedback_attachments__attachment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tickets_api_admin_feedback_tickets_get: {
        parameters: {
            query?: {
                status?: string | null;
                category?: string | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTicketListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_stats_api_admin_feedback_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackStatsOut"];
                };
            };
        };
    };
    read_ticket_api_admin_feedback_tickets__ticket_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTicketDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_ticket_api_admin_feedback_tickets__ticket_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_status_api_admin_feedback_tickets__ticket_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTicketDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reply_to_ticket_api_admin_feedback_tickets__ticket_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTicketDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ready_api_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
